language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y git gcc make re2c libpcre3-dev
  - travis_retry git clone https://github.com/phalcon/zephir
  - travis_retry cd zephir && ./install -c && cd ..
  - travis_retry mkdir codeclimate && cd codeclimate && composer require --no-interaction codeclimate/php-test-reporter:dev-master && cd ..
  - zephir build
  - echo "extension=csrfprotect.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - phpunit --verbose --coverage-text --coverage-clover=coverage.xml

after_script:
  - codeclimate/vendor/bin/test-reporter --coverage-report coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  code_climate:
    repo_token: 6316411d7a006bbe9742edb5462e63fac433ace5050cf3ffd448f0e19f61355d
